name: Build, Test and Publish
on:
  release:
    types: [ published ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: dotnet test --verbosity normal
  
  publish-senko-core:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Create the package
        run: dotnet pack Source/Senko.Core -c Release -p:Version=${{ github.event.release.tag_name }}

      - name: Push NuGet
        run: dotnet nuget push Source/Senko.Core/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

  publish-senko-bootstrap:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Create the package
        run: dotnet pack Source/Senko.Bootstrap -c Release -p:Version=${{ github.event.release.tag_name }}

      - name: Push NuGet
        run: dotnet nuget push Source/Senko.Bootstrap/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

  publish-senko-discord:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Create the package
        run: dotnet pack Source/Senko.Discord -c Release -p:Version=${{ github.event.release.tag_name }}

      - name: Push NuGet
        run: dotnet nuget push Source/Senko.Discord/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate